CREATE SCHEMA IF NOT EXISTS wz_db;

CREATE TABLE IF NOT EXISTS wz_db.demo (
  id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(200) NULL,
  `password` VARCHAR(200) NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;